Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "generic/ubuntu2004"

  # Master Node
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      # Disable swap
      swapoff -a
      sed -i '/swap/d' /etc/fstab

      # Install Containerd
      apt-get update
      apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get install -y containerd.io

      # Configure Containerd
      mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      systemctl restart containerd
      
      # Install required tools
      sudo apt-get install -y bridge-utils

      # Load kernel modules
      sudo modprobe br_netfilter
      echo "br_netfilter" | sudo tee /etc/modules-load.d/br_netfilter.conf
      # Enable required sysctl params
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf > /dev/null
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF
     # cat <<EOF > /etc/sysctl.d/99-kubernetes-cri.conf
     # net.bridge.bridge-nf-call-iptables = 1
     # net.bridge.bridge-nf-call-ip6tables = 1
     # net.ipv4.ip_forward = 1
     # EOF

      echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
      sysctl net.ipv4.ip_forward

      # Add Kubernetes GPG key
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg

      # Add Kubernetes repository
      echo "deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list


      # Install kubeadm, kubelet, and kubectl
      #curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      #echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      #echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
      apt-get update
      apt-get install -y kubelet kubeadm kubectl
      apt-mark hold kubelet kubeadm kubectl

      # Initialize Kubernetes Master
      kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.110

      # Configure kubectl for the vagrant user
      mkdir -p /home/vagrant/.kube
      cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      chown vagrant:vagrant /home/vagrant/.kube/config

      # Install Flannel network plugin
      #su - vagrant -c "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
      su - vagrant -c "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml"
    SHELL
  end

  # Worker Node 1
  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.56.111"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
    worker1.vm.provision "shell", inline: <<-SHELL
      # Disable swap
      swapoff -a
      sed -i '/swap/d' /etc/fstab

      # Install Containerd
      apt-get update
      apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get install -y containerd.io

      # Configure Containerd
      mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      systemctl restart containerd
      
      # Install required tools
      sudo apt-get install -y bridge-utils

      # Load kernel modules
      sudo modprobe br_netfilter
      echo "br_netfilter" | sudo tee /etc/modules-load.d/br_netfilter.conf

      # Enable required sysctl params
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf > /dev/null
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF
      #cat <<EOF > /etc/sysctl.d/99-kubernetes-cri.conf
      #  net.bridge.bridge-nf-call-iptables = 1
      #  net.bridge.bridge-nf-call-ip6tables = 1
      #  net.ipv4.ip_forward = 1
      #EOF

      echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
      sysctl net.ipv4.ip_forward

     



      # Add Kubernetes GPG key
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg

      # Add Kubernetes repository
      echo "deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
      
      # Install kubeadm, kubelet, and kubectl
      #curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      #echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      apt-get update
      apt-get install -y kubelet kubeadm kubectl
      apt-mark hold kubelet kubeadm kubectl
    SHELL
  end

  # Worker Node 2
  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.56.112"
    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
    worker2.vm.provision "shell", inline: <<-SHELL
      # Disable swap
      swapoff -a
      sed -i '/swap/d' /etc/fstab

      # Install Containerd
      apt-get update
      apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get install -y containerd.io

      # Configure Containerd
      mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      systemctl restart containerd

      # Install required tools
      sudo apt-get install -y bridge-utils

      # Load kernel modules
      sudo modprobe br_netfilter
      echo "br_netfilter" | sudo tee /etc/modules-load.d/br_netfilter.conf

      # Enable required sysctl params
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf > /dev/null
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF
      #cat <<EOF > /etc/sysctl.d/99-kubernetes-cri.conf
      #  net.bridge.bridge-nf-call-iptables = 1
      #  net.bridge.bridge-nf-call-ip6tables = 1
      #  net.ipv4.ip_forward = 1
      #EOF

      echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
      sysctl net.ipv4.ip_forward

      # Install kubeadm, kubelet, and kubectl
     
      # Add Kubernetes GPG key
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg

      # Add Kubernetes repository
      echo "deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

      #curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      #echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      apt-get update
      apt-get install -y kubelet kubeadm kubectl
      apt-mark hold kubelet kubeadm kubectl
    SHELL
  end
end
